### ISSUE TITLE
`activerdf` requires old versions for some tools / dependencies to work

### ISSUE THREAD

**Issue by ckristo** [ActiveRDF/ActiveRDF#13]
Hi,

I currently try to get one of the examples to run, and had several issues I want to document for others:
- The library runs only with Ruby 1.8 (see #9)
- You'll need to downgrade RubyGems to 1.8.X (`gem update --system 1.8.30`)
- The 'mime-types' gem is required in versions below 2.0 (`gem 'mime-types', '< 2.0'`) -- otherwise you'll get the following error:

```
/Users/christoph/.rvm/gems/ruby-1.8.7-head@activerdf-example/gems/activerdf_rdflite-1.4.1/lib/activerdf_rdflite/rdflite.rb:11:in `require': no such file to load -- mime/types (LoadError)
    from /Users/christoph/.rvm/gems/ruby-1.8.7-head@activerdf-example/gems/activerdf_rdflite-1.4.1/lib/activerdf_rdflite/rdflite.rb:11
    from /Users/christoph/.rvm/gems/ruby-1.8.7-head@activerdf-example/gems/activerdf_rdflite-1.4.1/lib/activerdf_rdflite/init.rb:11:in `require'
    from /Users/christoph/.rvm/gems/ruby-1.8.7-head@activerdf-example/gems/activerdf_rdflite-1.4.1/lib/activerdf_rdflite/init.rb:11
    from /Users/christoph/.rvm/gems/ruby-1.8.7-head@activerdf-example/gems/gem_plugin-0.2.3/lib/gem_plugin.rb:134:in `require'
    from /Users/christoph/.rvm/gems/ruby-1.8.7-head@activerdf-example/gems/gem_plugin-0.2.3/lib/gem_plugin.rb:134:in `load'
    from /Users/christoph/.rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:214:in `each'
    from /Users/christoph/.rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:214:in `_deprecated_each'
    from /Users/christoph/.rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/deprecate.rb:63:in `send'
    from /Users/christoph/.rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/rubygems/deprecate.rb:63:in `each'
    from /Users/christoph/.rvm/gems/ruby-1.8.7-head@activerdf-example/gems/gem_plugin-0.2.3/lib/gem_plugin.rb:112:in `load'
    from /Users/christoph/.rvm/gems/ruby-1.8.7-head@activerdf-example/gems/activerdf-1.6.11/lib/active_rdf.rb:68
    from ./rdf_example.rb:7:in `require'
    from ./rdf_example.rb:7
```
- If you try to use activerdf_rdflite: The 'uuidtools' gem is required in versions below 2.0 (`gem 'uuidtools', '< 2.0'`) -- otherwise, this error will be thrown:

```
/Users/christoph/.rvm/gems/ruby-1.8.7-head@activerdf-example/gems/activerdf-1.6.11/lib/active_rdf/queryengine/ntriples_parser.rb:33:in `parse': uninitialized constant NTriplesParser::UUID (NameError)
    from /Users/christoph/.rvm/gems/ruby-1.8.7-head@activerdf-example/gems/activerdf_rdflite-1.4.1/lib/activerdf_rdflite/rdflite.rb:197:in `add_ntriples'
    from /Users/christoph/.rvm/gems/ruby-1.8.7-head@activerdf-example/gems/activerdf_rdflite-1.4.1/lib/activerdf_rdflite/rdflite.rb:186:in `load'
    from ./rdf_example.rb:13
```

After downgrading some tools / dependencies, I get this library to work at least...

**Comment by ckristo** [comment]
If there is interest, I could try to fix this issues above and provide a PR...
