### ISSUE TITLE
SparqlAdapter::initialize should call super(params)

### ISSUE THREAD

**Issue by jamsden** [ActiveRDF/ActiveRDF#2]
The call to super() does not provide the parameters for :read and :write. So the adapter is not set correctly when supporting SPARQL update.

Also the @reads and @writes instance variables should not be set in SparqlAdapter::initialize. They are handled by the superclass.

**Comment by ckristo** [comment]
I guess the same is true for `RDFLite` -- I have to set the `enabled` property of the adapter (for `RDFLite` and `SparqlAdapter`) explicitly to true, otherwise ActiveRDF will complain that it cannot find a data source:

```
/Users/christoph/.rvm/gems/ruby-1.8.7-head@activerdf-example/gems/activerdf-1.6.11/lib/active_rdf/federation/federation_manager.rb:26:in `query': cannot execute query without data sources (ActiveRdfError)
    from /Users/christoph/.rvm/gems/ruby-1.8.7-head@activerdf-example/gems/activerdf-1.6.11/lib/active_rdf/queryengine/query.rb:190:in `execute'
    from /Users/christoph/.rvm/gems/ruby-1.8.7-head@activerdf-example/gems/activerdf-1.6.11/lib/active_rdf/objectmanager/object_manager.rb:24:in `construct_classes'
    from /Users/christoph/Documents/Ausbildung/TU/033532 Medieninformatik/Bakk-Arbeit/Arbeit/examples/ruby/activerdf-example/rdf_example.rb:17
    from -e:1:in `load'
    from -e:1
```

The `enabled` property is set to true in the constructor of `ActiveRdfAdapter`, the superclass for all adapters...
