### ISSUE TITLE
It doesn't run on CRuby 1.9.2

### ISSUE THREAD

**Issue by reiz** [ActiveRDF/ActiveRDF#9]
Hi, 

I am using this lib in an open source project. The curious thing is that it works perfectly with JRuby and with CRuby 1.8.X. But as soon I start my app with CRuby 1.9.2 I get this Exception: 

activerdf-1.6.11/lib/active_rdf/objectmanager/resource.rb:3:in `require': /Users/reiz/.rvm/gems/ruby-1.9.2-p318@trophicweb/gems/activerdf-1.6.11/lib/active_rdf/objectmanager/namespace.rb:63: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\n' (SyntaxError)
    when RDFS::Resource: resource.uri
                        ^
/Users/reiz/.rvm/gems/ruby-1.9.2-p318@trophicweb/gems/activerdf-1.6.11/lib/active_rdf/objectmanager/namespace.rb:99: syntax error, unexpected keyword_end, expecting $end
    from /Users/reiz/.rvm/gems/ruby-1.9.2-p318@trophicweb/gems/activerdf-1.6.11/lib/active_rdf/objectmanager/resource.rb:3:in`<top (required)>'
    from /Users/reiz/.rvm/gems/ruby-1.9.2-p318@trophicweb/gems/activerdf-1.6.11/lib/active_rdf.rb:30:in `require'
    from /Users/reiz/.rvm/gems/ruby-1.9.2-p318@trophicweb/gems/activerdf-1.6.11/lib/active_rdf.rb:30:in`<top (required)>'
    from /Users/reiz/workspace/ruby/trophic-web/config/application.rb:4:in `require'
    from /Users/reiz/workspace/ruby/trophic-web/config/application.rb:4:in`<top (required)>'
    from /Users/reiz/.rvm/gems/ruby-1.9.2-p318@trophicweb/gems/railties-3.2.8/lib/rails/commands.rb:53:in `require'
    from /Users/reiz/.rvm/gems/ruby-1.9.2-p318@trophicweb/gems/railties-3.2.8/lib/rails/commands.rb:53:in`block in <top (required)>'
    from /Users/reiz/.rvm/gems/ruby-1.9.2-p318@trophicweb/gems/railties-3.2.8/lib/rails/commands.rb:50:in `tap'
    from /Users/reiz/.rvm/gems/ruby-1.9.2-p318@trophicweb/gems/railties-3.2.8/lib/rails/commands.rb:50:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

I found out that other people have the same issue. Any thoughts?

**Comment by marciomr** [comment]
I had the very same issue here.

**Comment by ckristo** [comment]
Same problem here with my CRuby 2.2 (2.2.1p85)
